FROM microsoft/windowsservercore

ENV sa_password _

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Install chocolatey
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://chocolatey.org/install.ps1 -OutFile c:\choco.ps1; \
    c:\choco.ps1

# Install modules (requirements for dsc) and tools (requirements for php/sql)
RUN powershell -Command \
    Install-PackageProvider Nuget -ForceBootstrap -Force; \
    Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted; \
    Install-Module xPSDesiredStateConfiguration -RequiredVersion "6.4.0.0" -Force -SkipPublisherCheck; \
    Install-Module xWebAdministration -RequiredVersion "1.18.0.0" -Force -SkipPublisherCheck; \
    Install-Module xPhp -RequiredVersion "1.2.0.0" -Force -SkipPublisherCheck; \
    choco install vcredist2015 -y; \
    choco install sqlserver-odbcdriver -y; \
    choco install vim -y

# Run setup.ps1
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/arnaud-landry/noah/version2/Setup_Docker/noahfront/setup.ps1 -OutFile c:\setup.ps1; \
    c:\setup.ps1
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/arnaud-landry/noah/version2/Setup_Docker/noahfront/start.ps1 -OutFile c:\start.ps1;

# test php from cli
RUN C:\php\php.exe -v

# Start script
CMD .\start -DbUser $env:DbUser -DbPassword $env:DbPassword

# Expose port 8000
EXPOSE 8000