FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Install choco and Windows features
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://chocolatey.org/install.ps1 -OutFile c:\choco.ps1; \
    c:\choco.ps1

RUN powershell -Command \
    Install-PackageProvider Nuget -ForceBootstrap -Force; \
    Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted; \
    Install-Module xPSDesiredStateConfiguration -RequiredVersion "6.4.0.0" -Force -SkipPublisherCheck; \
    Install-Module xWebAdministration -RequiredVersion "1.18.0.0" -Force -SkipPublisherCheck; \
    choco install vcredist2015 -y

# Run setup
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/arnaud-landry/noah/master/Setup_Docker/Noah_Front/setup.ps1 -OutFile c:\setup.ps1; \
    c:\setup.ps1

RUN C:\php\php-cgi.exe -f C:\inetpub\wwwroot\noah\phpinfo.php

# Expose port 8000
EXPOSE 8000

COPY index.html C:\noah\