FROM microsoft/iis

RUN powershell -NoProfile -Command \
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/arnaud-landry/noah/master/Setup_Docker/Noah_Front/setup.ps1 -OutFile c:\setup.ps1; \
    c:\setup.ps1

EXPOSE 8000

COPY index.html C:\noah\