FROM microsoft/windowsservercore

# Install Windows features
RUN powershell -Command \
    Install-PackageProvider Nuget -ForceBootstrap -Force; \
    Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted; \
    Install-Module xPSDesiredStateConfiguration -RequiredVersion "6.4.0.0" -Force -SkipPublisherCheck; \
    Install-Module xWebAdministration -RequiredVersion "1.18.0.0" -Force -SkipPublisherCheck

# Run setup
RUN powershell -executionpolicy bypass -NoProfile -Command \
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/arnaud-landry/noah/master/Setup_Docker/Noah_Front/setup.ps1 -OutFile c:\setup.ps1; \
    c:\setup.ps1

# Expose port 8000
EXPOSE 8000

COPY index.html C:\noah\